### ISSUE TITLE
Unexpected response '404 Not Found' from jira.

### ISSUE THREAD

**Issue by HyHyena** [ankitpokhrel/jira-cli#225]
Hey. I am really looking forward to use your program but got stuck on the init phase. Is it because of the oldness of my company's jira version or something else?

1. JiraCLI Version:
0.2.0
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
on-premise 6.2.1
3. What operating system are you using? Also mention version.
manjaro kernel version 5.10.79-1
4. What terminal are you using? Also mention version.
Konsole (konsole) 21.08.3-1

```jira init
? Installation type: Local
? Link to Jira server: https://jira.company.ru
? Login username: username
? Default project: PROJECT
⠙ Fetching boards for project 'PROJECT'... 
✗ Received unexpected response '404 Not Found' from jira. Please try again.
```

**Comment by ankitpokhrel** [comment]
@HyHyena Looks like you are using a project without board. This was fixed in #216. But the build is not yet available.

If you wish to use this fix for now, you can either [compile from source](https://github.com/ankitpokhrel/jira-cli#development) or if you are using homebrew you can build binary from `HEAD` (requires `make`, `git` and `go`)

```sh
brew uninstall jira-cli
brew install jira-cli --HEAD
``` 

Let me know if you still have problem with the head build.

**Comment by HyHyena** [comment]
Unfortunately that didn't help and I am still getting this error. Thanks for the fast feedback, I'll go find another job to use this tool :)

**Comment by ankitpokhrel** [comment]
I wonder why it didn't work for you with the new build but I cannot help much unless you can give me further details. Finding another job sounds like a good idea tho 😄

Please feel free to comment here or create a new issue if you find any details that could help figure out the issue.

**Comment by xuanyuanaosheng** [comment]
@HyHyena   Any update?
